Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 100
Metrics/ModuleLength:
  Max: 200
Metrics/ClassLength:
  Max: 1500
Metrics/BlockLength:
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/PerceivedComplexity:
  Max: 13
Metrics/AbcSize:
  Max: 100
Style/Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'temp_dir/**'
Style/FrozenStringLiteralComment:
  Enabled: false